# translation of src_debug_server.po to French
# Module src_debug_server translation file for language=en
# Copyright (C) 2003 Archaeopteryx Software, Inc.
# Wing Python IDE -- wingware.com
# Encolpe DEGOUTE <encolpe.degoute@free.fr>, 2004.
#
msgid ""
msgstr ""
"Project-Id-Version: src_debug_server\n"
"POT-Creation-Date: 2022-12-14 09:43-0500\n"
"PO-Revision-Date: 2018-08-25 23:20+0200\n"
"Last-Translator: Jean Sanchez <js.fr@protonmail.ch>\n"
"Language-Team: French\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.4\n"
"X-Generator: Poedit 2.1.1\n"

#: src/debug/tserver/abstract.py:355
msgid "Wing Debug Log File\n"
msgstr "Fichier de log de débogage de Wing\n"

#: src/debug/tserver/abstract.py:356
msgid "This file can be used to diagnose problems in debugger internals\n"
msgstr ""
"Ce file peut être utilisé pour diagnostiquer les problèmes dans les routines "
"du débogueur\n"

#: src/debug/tserver/abstract.py:357
msgid "For help, contact support@wingware.com\n"
msgstr "Pour de l'aide, contactez support@wingware.com\n"

#: src/debug/tserver/abstract.py:362
msgid "Warning:  Log file does not exist:\n"
msgstr "Avertissement : Le fichier de log n'existe pas :\n"

#: src/debug/tserver/abstract.py:364
msgid "Warning:  and could not be created; logging disabled\n"
msgstr "Avertissement : et ne peut pas être créé. Enregistrement désactivé.\n"

#: src/debug/tserver/abstract.py:367
msgid "Warning:  Log file is not a file:\n"
msgstr "Avertissement : Le fichier de log n'est pas un fichier :\n"

#: src/debug/tserver/abstract.py:369
msgid "Warning:  Logging disabled\n"
msgstr "Avertissement : Logging désactivé\n"

#: src/debug/tserver/dbginspect.py:59 src/debug/tserver/dbgserver.py:3118
#: src/debug/tserver/dbgutils.py:489 src/debug/tserver/dbgutils.py:515
msgid "(truncated)"
msgstr "(tronqué)"

#: src/debug/tserver/dbginspect.py:827 src/debug/tserver/dbginspect.py:891
#: src/debug/tserver/dbginspect.py:967 src/debug/tserver/dbginspect.py:1175
#: src/debug/tserver/dbginspect.py:1246 src/debug/tserver/dbginspect.py:1354
#: src/debug/tserver/dbgutils.py:480 src/debug/tserver/dbgutils.py:508
#: src/debug/tserver/dbgutils.py:2641
msgid " at %s"
msgstr ""

#: src/debug/tserver/dbginspect.py:832 src/debug/tserver/dbginspect.py:896
#: src/debug/tserver/dbginspect.py:1263 src/debug/tserver/dbgutils.py:235
#, fuzzy
msgid "<opaque %s%s>"
msgstr "<opaque "

#: src/debug/tserver/dbginspect.py:918
#, fuzzy
msgid "<huge %s%s; len=%s>"
msgstr "<énorme %s à %s ; longueur=%i>"

#: src/debug/tserver/dbginspect.py:973 src/debug/tserver/dbginspect.py:994
#: src/debug/tserver/dbgutils.py:517 src/debug/tserver/dbgutils.py:2652
#: src/debug/tserver/dbgutils.py:2657
#, fuzzy
msgid "<huge %s%s; len=%i>"
msgstr "<énorme %s à %s ; longueur=%i>"

#: src/debug/tserver/dbginspect.py:1194 src/debug/tserver/dbgutils.py:2659
#, fuzzy
msgid "<huge %s%s>"
msgstr "<énorme %s à %s ; longueur=%i>"

#: src/debug/tserver/dbgserver.py:1349
msgid "<module>"
msgstr "<module>"

#: src/debug/tserver/dbgserver.py:1492
msgid "<error evaluating>"
msgstr "<erreur durant l'évaluation>"

#: src/debug/tserver/dbgserver.py:2089 src/debug/tserver/dbgserver.py:2125
msgid "<thread %i is running>"
msgstr "<la tâche %i est en cours>"

#: src/debug/tserver/dbgserver.py:2092 src/debug/tserver/dbgserver.py:2128
msgid "<invalid thread id %s or stack index %s>"
msgstr "<id de tâche %s ou index de pile %s invalide>"

#: src/debug/tserver/dbgserver.py:2094 src/debug/tserver/dbgserver.py:2130
msgid "<invalid stack frame>"
msgstr "<élément de pile invalide>"

#: src/debug/tserver/dbgserver.py:2158 src/debug/tserver/dbgserver.py:2187
msgid "<sys.modules does not exist>"
msgstr "<sys.modules n'existe pas>"

#: src/debug/tserver/dbgserver.py:2161 src/debug/tserver/dbgserver.py:2192
msgid "<error accessing sys.modules>"
msgstr "<erreur en accédant à sys.modules>"

#: src/debug/tserver/dbgserver.py:2189
msgid "<no longer exists"
msgstr "<n'existe plus"

#: src/debug/tserver/dbgserver.py:2237 src/debug/tserver/dbgserver.py:2290
msgid "<no longer exists>"
msgstr "<n'existe plus>"

#: src/debug/tserver/dbgserver.py:2268 src/debug/tserver/dbgserver.py:4647
msgid "<parent too large>"
msgstr "<parent trop large>"

#: src/debug/tserver/dbgserver.py:2270 src/debug/tserver/dbgserver.py:4649
msgid "<invalid parent type>"
msgstr "<type de parent invalide>"

#: src/debug/tserver/dbgserver.py:2280 src/debug/tserver/dbgserver.py:2749
msgid "<value not found>"
msgstr "<valuer non trouvée>"

#: src/debug/tserver/dbgserver.py:2737
msgid "<thread is running>"
msgstr "<tâche en cours>"

#: src/debug/tserver/dbgserver.py:2739
msgid "<invalid context>"
msgstr "<contexte invalide>"

#: src/debug/tserver/dbgserver.py:4655
msgid "<invalid path %s at pos=%i>"
msgstr "<chemin %s invalide à la position=%i>"

#: src/debug/tserver/dbgutils.py:152
msgid "<undefined>"
msgstr "<indéfini>"

#: src/debug/tserver/dbgutils.py:168
msgid "at"
msgstr "à"

#: src/debug/tserver/dbgutils.py:178
msgid "len=%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:188 src/debug/tserver/dbgutils.py:2753
#, fuzzy
msgid "<error handling value>"
msgstr "<erreur durant l'évaluation>"

#: src/debug/tserver/dbgutils.py:190
msgid "<timeout>"
msgstr ""

#: src/debug/tserver/dbgutils.py:198
msgid "<huge "
msgstr ""

#: src/debug/tserver/dbgutils.py:218
msgid "<long "
msgstr ""

#: src/debug/tserver/dbgutils.py:736 src/debug/tserver/dbgutils.py:748
msgid ", pos "
msgstr ", position "

#: src/debug/tserver/dbgutils.py:752
msgid ", line "
msgstr ", ligne "

#: src/debug/tserver/dbgutils.py:754
msgid "SyntaxError: "
msgstr "Erreur de syntaxe : "

#: src/debug/tserver/dbgutils.py:782
msgid "Error"
msgstr "Erreur"

#: src/debug/tserver/dbgutils.py:792
msgid "Error: Wing was unable to pack up an exception message"
msgstr "Erreur : Wing n'a pas été capable de générer un message d'exception"

#: src/debug/tserver/dbgutils.py:3668 src/debug/tserver/dbgutils.py:3684
msgid "Key"
msgstr ""

#: src/debug/tserver/dbgutils.py:3668 src/debug/tserver/dbgutils.py:3684
msgid "Value"
msgstr "Valeur"

#: src/debug/tserver/dbgutils.py:3679 src/debug/tserver/dbgutils.py:3706
msgid "Item"
msgstr ""

#: src/debug/tserver/netserver.py:475
msgid "Redirected I/O failed on closed debug connection"
msgstr ""
"La redirection des E/S a échoué lors de la fermeture de la connexion de "
"débogage"

#: src/debug/tserver/netserver.py:638
msgid "EOF when reading a line"
msgstr "EOF lors de la lecture d'une ligne"

#: src/debug/tserver/netserver.py:1213
msgid "(unavailable)"
msgstr "(indisponible)"

#: src/debug/tserver/netserver.py:1483
msgid "[omitting some output]"
msgstr "[omet quelques sorties]"

#: src/debug/tserver/startdebug.py:233 src/debug/tserver/startdebug.py:367
#, fuzzy
msgid "wingdb.py: Error: Debug file does not exist:"
msgstr "Avertissement : Le fichier de log n'existe pas :\n"

#: src/debug/tserver/startdebug.py:237 src/debug/tserver/startdebug.py:371
#, fuzzy
msgid "wingdb.py: Error: Debug file is not a file:"
msgstr "Avertissement : Le fichier de log n'est pas un fichier :\n"

#: src/debug/tserver/startdebug.py:420
msgid "Network peer is "
msgstr ""

#: src/debug/tserver/startdebug.py:421
msgid "Attach port = "
msgstr ""

#: src/debug/tserver/startdebug.py:422
msgid "Initial stop = "
msgstr ""

#: src/debug/tserver/startdebug.py:436
msgid "wingdb.py: Could not create debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:454
msgid "wingdb.py: Running %s"
msgstr ""

#: src/debug/tserver/startdebug.py:465 src/debug/tserver/startdebug.py:492
msgid "wingdb.py: Server exiting abnormally on exception"
msgstr ""

#: src/debug/tserver/startdebug.py:663
msgid "wingdb.py: Error: Failed to start the debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:664
msgid "wingdb.py: Error: You may be running an unsupported version of Python"
msgstr ""

#: src/debug/tserver/startdebug.py:665
msgid "wingdb.py: Python version = %s"
msgstr ""

#: src/debug/tserver/startdebug.py:755 src/debug/tserver/startdebug.py:757
msgid "-- Type return or enter to exit --\n"
msgstr ""

#~ msgid "<opaque"
#~ msgstr "<opaque"

#~ msgid "<unknown type>"
#~ msgstr "<type inconnu>"

#~ msgid "Value too large to evaluate: "
#~ msgstr "Value trop grande pour être évaluée : "

#~ msgid "<invalid path registration>"
#~ msgstr "<enregistrement de chemin invalide>"

#~ msgid "Function"
#~ msgstr "Fonction"

#~ msgid "Method"
#~ msgstr "Méthode"

#, fuzzy
#~ msgid "Could not execute because an error occurred:\n"
#~ msgstr ""
#~ "Impossible de lancer le programme car il y a eu une erreur:\n"
#~ "\n"

#~ msgid "Error: Runtime exception occurred"
#~ msgstr "Erreur: Obtention d'une erreur d'exécution"

#~ msgid "Default User"
#~ msgstr "Utilisateur par défaut"
