# Module src_wingbase translation file for language=en
# Copyright (C) 2016 Wingware
# Wingware Python IDE -- www.wingware.com
#
msgid ""
msgstr ""
"Project-Id-Version: 6.0.0\n"
"POT-Creation-Date: 2022-12-14 09:49-0500\n"
"PO-Revision-Date: 2019-05-06 22:21+0200\n"
"Last-Translator: Jean Sanchez <js.fr@protonmail.ch>\n"
"Language-Team: None\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 2.2.1\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Poedit-SourceCharset: UTF-8\n"

#: src/wingbase/containers.py:276 src/wingbase/remoteclient.py:376
msgid "File exceeds configured maximum size (%.1fMB>%.0fMB)"
msgstr ""

#: src/wingbase/filefilter.py:60
msgid "Wild Card on File Name"
msgstr "Joker sur le nom de fichier"

#: src/wingbase/filefilter.py:61
msgid "Mime Type"
msgstr "Type Mime"

#: src/wingbase/filefilter.py:62
msgid "Wild Card on Directory Name"
msgstr "Joker sur le nom de répertoire"

#: src/wingbase/filefilter.py:428 src/wingbase/filefilter.py:433
#: src/wingbase/filefilter.py:440
msgid "Invalid or empty filter %s spec pos=%i: '%s'"
msgstr "Filtre invalide ou vide %s spec à la position = %i : '%s'"

#: src/wingbase/filefilter.py:435
msgid "Bad mime type in filter %s spec pos=%i: '%s'"
msgstr "Mauvais type mime dans le filtre %s spec à la position = %i : '%s'"

#: src/wingbase/filefilter.py:444
msgid "Unknown filter %s spec type pos=%i: '%s'"
msgstr "Filtre inconnu %s spec type à la position=%i : '%s'"

#: src/wingbase/mime.py:135
msgid "Wing Project"
msgstr "Projet Wing"

#: src/wingbase/mime.py:136
msgid "Python Interface"
msgstr "Interface Python"

#: src/wingbase/mime.py:538 src/wingbase/mime.py:540 src/wingbase/mime.py:615
msgid "%s File"
msgstr "Fichier %s"

#: src/wingbase/remoteclient.py:991
msgid "Missing remote host configuration for %s"
msgstr "Il manque la configuration de l’hôte à distance pour %s"

#: src/wingbase/remoteclient.py:1252
msgid ""
"Remote server %s failed to connect (hostname=%s, winghome=%s, pyexec=%s)"
msgstr ""

#: src/wingbase/remoteclient.py:1262
msgid "Remote server to %s is unused -- closing connection"
msgstr ""
"Le serveur à distance vers %s est inutilisé — connection en cours de "
"fermeture"

#: src/wingbase/remoteclient.py:1665
#, fuzzy
msgid ""
"Reverse SSH tunnel startup timed out -- connection ID not seen after %.2f "
"seconds"
msgstr "Délai expiré — pas de sorties vues en >3 secondes"

#: src/wingbase/remoteclient.py:1860
msgid "Reverse tunnel to %s (%i<->%i) failed after %i retries"
msgstr ""

#: src/wingbase/remoteclient.py:1865
msgid "Reverse tunnel to %s (%i<->%i) is unused -- closing connection"
msgstr ""

#: src/wingbase/textutils.py:1079
msgid "Unable to convert to unicode.  Tried encodings: %s."
msgstr "Impossible de convertir en unicode. Encodages essayés : %s."

#: src/wingbase/updateutils.py:173
msgid "Corrupt catalog: Missing | in line: "
msgstr ""

#: src/wingbase/updateutils.py:185
msgid "Corrupt catalog: Invalid line type: "
msgstr ""

#: src/wingbase/updateutils.py:334
msgid "Version spec on line %i is too short"
msgstr ""

#: src/wingbase/updateutils.py:338
msgid "Bad version %s on line %i"
msgstr ""

#: src/wingbase/updateutils.py:350
msgid "Bad release type %s on line %i"
msgstr ""

#: src/wingbase/updateutils.py:354
msgid "Bad release flag %s on line %i"
msgstr ""

#: src/wingbase/updateutils.py:359
msgid "Line %i lists summary before version"
msgstr ""

#: src/wingbase/updateutils.py:362
msgid "Bad change summary on line %i"
msgstr ""

#: src/wingbase/updateutils.py:365
msgid "Bad product type on line %i"
msgstr ""

#: src/wingbase/updateutils.py:368
msgid "Bad change type on line %i"
msgstr ""

#: src/wingbase/updateutils.py:500
msgid "Some unpatchable files changed:"
msgstr ""

#: src/wingbase/updateutils.py:504
msgid "No changes for the update"
msgstr "Pas de modifications pour la mise-à-jour"

#: src/wingbase/updateutils.py:537
msgid "Could not create update tarfile:"
msgstr ""

#: src/wingbase/updateutils.py:643
msgid "Updates are corrupt and need to be removed and reinstalled"
msgstr ""

#: src/wingbase/updateutils.py:693
msgid "Failed to delete old busy update: %s"
msgstr ""

#: src/wingbase/updateutils.py:696
msgid "Possibly concurrent update/merge on %s"
msgstr ""

#: src/wingbase/updateutils.py:704
msgid "Renaming %s failed; skipping update merge"
msgstr ""

#: src/wingbase/updateutils.py:737
msgid "Failed to merge update directories: %s -> %s; aborting merge"
msgstr ""

#: src/wingbase/updateutils.py:915
msgid "Missing file: %s"
msgstr "Fichier manquant : %s"

#: src/wingbase/updateutils.py:919
msgid "Invalid Type: %s (expected file but found non-file)"
msgstr ""

#: src/wingbase/updateutils.py:921
msgid "Invalid Type: %s (expected directory but found non-directory)"
msgstr ""

#: src/wingbase/updateutils.py:926
msgid "Read failed:  %s"
msgstr "Lecture échouée : %s"

#: src/wingbase/updateutils.py:929
msgid "Changed file: %s"
msgstr "Fichier modifié : %s"

#~ msgid "Unknown"
#~ msgstr "Inconnu"
