msgid ""
msgstr ""
"Project-Id-Version: src_debug_tserver\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-12-14 09:52-0500\n"
"PO-Revision-Date: 2018-03-18 22:27+0300\n"
"Last-Translator: alexandr\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10 >= 2 && n"
"%10<=4 &&(n%100<10||n%100 >= 20)? 1 : 2);\n"
"X-Generator: Loco https://localise.biz\n"
"X-Loco-Source-Locale: en\n"
"X-Loco-Project-Id: 44387\n"
"X-Loco-Api-Version: 1.0.19 20180317-1\n"

#: src/debug/tserver/abstract.py:355
msgid "Wing Debug Log File\n"
msgstr "Файл журнала отладки Wing"

#: src/debug/tserver/abstract.py:356
msgid "This file can be used to diagnose problems in debugger internals\n"
msgstr ""
"Этот файл можно использовать для диагностики проблем во внутренних "
"компонентах отладчика"

#: src/debug/tserver/abstract.py:357
msgid "For help, contact support@wingware.com\n"
msgstr "За помощью обращайтесь по адресу support@wingware.com"

#: src/debug/tserver/abstract.py:362
msgid "Warning:  Log file does not exist:\n"
msgstr "Предупреждение: файл журнала не существует:"

#: src/debug/tserver/abstract.py:364
msgid "Warning:  and could not be created; logging disabled\n"
msgstr "Предупреждение: и не удалось создать; ведение журнала отключено"

#: src/debug/tserver/abstract.py:367
msgid "Warning:  Log file is not a file:\n"
msgstr "Предупреждение: файл журнала не является файлом:"

#: src/debug/tserver/abstract.py:369
msgid "Warning:  Logging disabled\n"
msgstr "Предупреждение: ведение журнала отключено"

#: src/debug/tserver/dbginspect.py:59 src/debug/tserver/dbgserver.py:3118
#: src/debug/tserver/dbgutils.py:489 src/debug/tserver/dbgutils.py:515
msgid "(truncated)"
msgstr ""

#: src/debug/tserver/dbginspect.py:827 src/debug/tserver/dbginspect.py:891
#: src/debug/tserver/dbginspect.py:967 src/debug/tserver/dbginspect.py:1175
#: src/debug/tserver/dbginspect.py:1246 src/debug/tserver/dbginspect.py:1354
#: src/debug/tserver/dbgutils.py:480 src/debug/tserver/dbgutils.py:508
#: src/debug/tserver/dbgutils.py:2641
msgid " at %s"
msgstr ""

#: src/debug/tserver/dbginspect.py:832 src/debug/tserver/dbginspect.py:896
#: src/debug/tserver/dbginspect.py:1263 src/debug/tserver/dbgutils.py:235
#, fuzzy
msgid "<opaque %s%s>"
msgstr "<непрозрачный "

#: src/debug/tserver/dbginspect.py:918
#, fuzzy
msgid "<huge %s%s; len=%s>"
msgstr "<очень большой %s в %s; len=%i>"

#: src/debug/tserver/dbginspect.py:973 src/debug/tserver/dbginspect.py:994
#: src/debug/tserver/dbgutils.py:517 src/debug/tserver/dbgutils.py:2652
#: src/debug/tserver/dbgutils.py:2657
#, fuzzy
msgid "<huge %s%s; len=%i>"
msgstr "<очень большой %s в %s; len=%i>"

#: src/debug/tserver/dbginspect.py:1194 src/debug/tserver/dbgutils.py:2659
#, fuzzy
msgid "<huge %s%s>"
msgstr "<очень большой %s в %s; len=%i>"

#: src/debug/tserver/dbgserver.py:1349
msgid "<module>"
msgstr "<модуль>"

#: src/debug/tserver/dbgserver.py:1492
msgid "<error evaluating>"
msgstr "<оценка ошибок>"

#: src/debug/tserver/dbgserver.py:2089 src/debug/tserver/dbgserver.py:2125
msgid "<thread %i is running>"
msgstr "<поток %i запущен>"

#: src/debug/tserver/dbgserver.py:2092 src/debug/tserver/dbgserver.py:2128
msgid "<invalid thread id %s or stack index %s>"
msgstr "<Неверный поток id %s или указатель стека  %s>"

#: src/debug/tserver/dbgserver.py:2094 src/debug/tserver/dbgserver.py:2130
msgid "<invalid stack frame>"
msgstr "<недопустимый фрейм стека>"

#: src/debug/tserver/dbgserver.py:2158 src/debug/tserver/dbgserver.py:2187
msgid "<sys.modules does not exist>"
msgstr "<sys.modules не существует>"

#: src/debug/tserver/dbgserver.py:2161 src/debug/tserver/dbgserver.py:2192
msgid "<error accessing sys.modules>"
msgstr "<ошибка доступа sys.modules>"

#: src/debug/tserver/dbgserver.py:2189
msgid "<no longer exists"
msgstr "<больше не существует"

#: src/debug/tserver/dbgserver.py:2237 src/debug/tserver/dbgserver.py:2290
msgid "<no longer exists>"
msgstr "<более не существует>"

#: src/debug/tserver/dbgserver.py:2268 src/debug/tserver/dbgserver.py:4647
msgid "<parent too large>"
msgstr "<слишком большое значение родителя>"

#: src/debug/tserver/dbgserver.py:2270 src/debug/tserver/dbgserver.py:4649
msgid "<invalid parent type>"
msgstr "<неверный тип родителя>"

#: src/debug/tserver/dbgserver.py:2280 src/debug/tserver/dbgserver.py:2749
msgid "<value not found>"
msgstr "<значение не найдено>"

#: src/debug/tserver/dbgserver.py:2737
msgid "<thread is running>"
msgstr "<поток запущен>"

#: src/debug/tserver/dbgserver.py:2739
msgid "<invalid context>"
msgstr "<недопустимый контекст>"

#: src/debug/tserver/dbgserver.py:4655
msgid "<invalid path %s at pos=%i>"
msgstr "<неверный путь %s в pos=%i>"

#: src/debug/tserver/dbgutils.py:152
msgid "<undefined>"
msgstr ""

#: src/debug/tserver/dbgutils.py:168
msgid "at"
msgstr ""

#: src/debug/tserver/dbgutils.py:178
msgid "len=%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:188 src/debug/tserver/dbgutils.py:2753
#, fuzzy
msgid "<error handling value>"
msgstr "<оценка ошибок>"

#: src/debug/tserver/dbgutils.py:190
msgid "<timeout>"
msgstr ""

#: src/debug/tserver/dbgutils.py:198
msgid "<huge "
msgstr ""

#: src/debug/tserver/dbgutils.py:218
msgid "<long "
msgstr ""

#: src/debug/tserver/dbgutils.py:736 src/debug/tserver/dbgutils.py:748
msgid ", pos "
msgstr ", поз "

#: src/debug/tserver/dbgutils.py:752
msgid ", line "
msgstr ", строка "

#: src/debug/tserver/dbgutils.py:754
msgid "SyntaxError: "
msgstr "Ошибка синтаксиса: "

#: src/debug/tserver/dbgutils.py:782
msgid "Error"
msgstr "Ошибка"

#: src/debug/tserver/dbgutils.py:792
msgid "Error: Wing was unable to pack up an exception message"
msgstr "Ошибка: Wing не смог собрать сообщение об исключении"

#: src/debug/tserver/dbgutils.py:3668 src/debug/tserver/dbgutils.py:3684
msgid "Key"
msgstr ""

#: src/debug/tserver/dbgutils.py:3668 src/debug/tserver/dbgutils.py:3684
msgid "Value"
msgstr ""

#: src/debug/tserver/dbgutils.py:3679 src/debug/tserver/dbgutils.py:3706
msgid "Item"
msgstr ""

#: src/debug/tserver/netserver.py:475
msgid "Redirected I/O failed on closed debug connection"
msgstr "Сбой перенаправленного ввода-вывода при закрытом отладочном соединении"

#: src/debug/tserver/netserver.py:638
msgid "EOF when reading a line"
msgstr "EOF при чтении строки"

#: src/debug/tserver/netserver.py:1213
msgid "(unavailable)"
msgstr "(недоступен)"

#: src/debug/tserver/netserver.py:1483
msgid "[omitting some output]"
msgstr "[опуская некоторый вывод]"

#: src/debug/tserver/startdebug.py:233 src/debug/tserver/startdebug.py:367
#, fuzzy
msgid "wingdb.py: Error: Debug file does not exist:"
msgstr "Предупреждение: файл журнала не существует:"

#: src/debug/tserver/startdebug.py:237 src/debug/tserver/startdebug.py:371
#, fuzzy
msgid "wingdb.py: Error: Debug file is not a file:"
msgstr "Предупреждение: файл журнала не является файлом:"

#: src/debug/tserver/startdebug.py:420
msgid "Network peer is "
msgstr ""

#: src/debug/tserver/startdebug.py:421
msgid "Attach port = "
msgstr ""

#: src/debug/tserver/startdebug.py:422
msgid "Initial stop = "
msgstr ""

#: src/debug/tserver/startdebug.py:436
msgid "wingdb.py: Could not create debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:454
msgid "wingdb.py: Running %s"
msgstr ""

#: src/debug/tserver/startdebug.py:465 src/debug/tserver/startdebug.py:492
msgid "wingdb.py: Server exiting abnormally on exception"
msgstr ""

#: src/debug/tserver/startdebug.py:663
msgid "wingdb.py: Error: Failed to start the debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:664
msgid "wingdb.py: Error: You may be running an unsupported version of Python"
msgstr ""

#: src/debug/tserver/startdebug.py:665
msgid "wingdb.py: Python version = %s"
msgstr ""

#: src/debug/tserver/startdebug.py:755 src/debug/tserver/startdebug.py:757
msgid "-- Type return or enter to exit --\n"
msgstr ""

#, fuzzy
#~ msgid "<opaque"
#~ msgstr "<непрозрачный "
